language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  global:
    - REPO_NAME=RatchetModelPush
    - PLUGIN_NAME=RatchetModelPush
    - COMPOSER_VENDOR=Vendor
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=master
    - DB=mysql CAKE_VERSION=2.5

matrix:
  allow_failures:
    - php: hhvm

  include:
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master COVERALLS=1
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master PHPCS=1
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master FOC_VALIDATE=1

before_script:
  - git clone https://github.com/WyriHaximus/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  webhooks:
    urls:
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true
